### ISSUE TITLE
关于组合、聚合的uml图的错误

### ISSUE THREAD

**Issue by kate2014** [fujohnwang/unveil-springboot-feedbacks#12]
作者对于组合、聚合的uml图是否理解有偏差，A包含B ，菱形应该在A这边，第63页、第75页的图应该错了。

**Comment by 011011100010110101101111** [comment]
@kate2014 你说的这个具体是在第几章第几节？我亚马逊买的电子书页码跟纸质书不太一样。

**Comment by fujohnwang** [comment]
@kate2014 你说的对， 方向是错了。

**Comment by fujohnwang** [comment]
@kate2014 你说的对， 方向是错了。下回如果再版， 我会让出版社修正一下
