### ISSUE TITLE
2.2 插图出现错误

### ISSUE THREAD

**Issue by 011011100010110101101111** [fujohnwang/unveil-springboot-feedbacks#15]
2.2 spring ioc 其实很简单的 图2-1 Ioc 相关概念示意图 中出现错误

Dependency Lookup 的简写应该是DL ，图中 都是DI

**Comment by fujohnwang** [comment]
应该是出版社重新画图的时候搞错了， 下回再版让他们重新改下，原图是对的

**Comment by fujohnwang** [comment]
应该是第一版的sh'h时候出版社重新画图搞错了， 再版的应该都改过来了

![30f7b192e73428f38f309900984e9f07](https://user-images.githubusercontent.com/451506/33523462-085f2334-d843-11e7-8da7-a572b6b83ab7.jpg)
![abdcfd7d85c85bdf61f9079e3f2cec45](https://user-images.githubusercontent.com/451506/33523463-08b40f5c-d843-11e7-9fdd-bc049aee4a6e.jpg)
