### ISSUE TITLE
求扶墙老师让再印刷《Spring揭秘》，京东淘宝盗版书都炒到500了，但是印刷质量方面连图都看不清

### ISSUE THREAD

**Issue by engineerping** [fujohnwang/unveil-springboot-feedbacks#17]
![cca3ee4495d740a1c6377f36b2edc73](https://user-images.githubusercontent.com/47186985/175799566-77d8c638-537e-4ec3-ba8f-eb85508c6eab.jpg)

**Comment by fujohnwang** [comment]
实在不好意思哈， 这本书早就脱离我的能力范围了，不管是国内的出版环境还是出版方，这些因素都不是我能掌控的，我能做的只是给大家带来好的内容。 

依然要谢谢你，让我知道这本书居然这么贵了...
