### ISSUE TITLE
王老师，那个28页第9步应该是错的吧？

### ISSUE THREAD

**Issue by tbahh** [fujohnwang/unveil-springboot-feedbacks#19]
第9步只是注册了 @EnableAutoConfiguration所在的类，也就是main方法所在类的bean定义信息。具体自动注入的其他bean信息应该是在refresh中完成的。。。。。

**Comment by tbahh** [comment]
另外请教个问题，像这种一个代码里面如果涉及很复杂的代码，一般是般是如何阅读的，如何确定其影响范围或职责

**Comment by fujohnwang** [comment]
> 第9步只是注册了 @EnableAutoConfiguration所在的类，也就是main方法所在类的bean定义信息。具体自动注入的其他bean信息应该是在refresh中完成的。。。。。

时间比较久远，我没法回头看哈，有可能是错的，如果是错的，你能发现，那最好了；）
也不排除随着版本的变化，代码逻辑有调整。

另外，我一般是导入Intellij IDEA读代码，先对来说跳转查找会更习惯一些（不能说最方便，只是习惯这个工具），像vscode之类，如果你很熟悉，也可以的，毕竟，代码也是文本，只不过有些关系分析和跳转的支持和配合，会更方便厘清代码之间的关系。

**Comment by tbahh** [comment]
；）
