### ISSUE TITLE
凌晨2点，刚看完，说说对本书的评价吧。

### ISSUE THREAD

**Issue by notreami** [fujohnwang/unveil-springboot-feedbacks#3]
5月初就预定本书了，刚收到快递就马不停蹄的阅读，这会刚看完（应该算是比较快吧，大约花了2天多的时间）说是对本书的感受：
本书从微服务的讲解引出spring boot，并对spring boot的工作流程和实践做了不错的讲解，最棒的是引出的docker、scala与spring boot结合。（这正是我买这本书的原因，官网或者网络上对spring boot的使用都非常简陋）。

但是不得不吐槽两句（对于开发，个人比较喜欢吐槽那些觉得可以做的更好但没有去做的事）：
1，spring boot都推行约定优于配置（Convention Over Configuration）,作者居然还用maven的pom.xml配置，完全可以改用gradle来构建项目，或者使用maven 3的特性Polyglot Maven，但却还在使用pom.xml配置，一个pom.xml配置就能占好几页纸，本来书就薄（这让spring boot的初衷很忧伤（貌似官网也是倾向于对maven的xml配置））。

2，spring boot都出到1.4.0 M3了，本书居然还有基于1.2.6的代码，而且纵观全本，对1.3.x最上心的居然是Banner，而不是devtools（个人对热插拔非常热衷，以及本书研究的版本略显陈旧）。

以上是个人感觉，总之，书里谈论的内容不错，但不够完美～～

**Comment by fujohnwang** [comment]
hehe , 你的初衷可以理解， 但是：
1. 技术选型上每个人口味的不一样， 是gradle还是maven，甚至其他构建工具， 如果只是个人开发， 怎么选都可以，但如果是团队， 那么，我选择保守稳定的，通过工具化等支持提升你说的那些繁琐的事情，整体效率 》 单结点效率；
2. 书的写作和出版牵扯周期比较长，如果你能了解这个特点， 那就没有什么好纠结的了；

感谢购买和阅读  ；）
