### ISSUE TITLE
是不是把书上的源码公开一下

### ISSUE THREAD

**Issue by liang412528974** [fujohnwang/unveil-springboot-feedbacks#4]
是不是把书上的源码公开一下，好让我们能完整的看一下

**Comment by edocevol** [comment]
是啊，书上的部分代码敲出来找不到对应的声明的地方，比如56页的name()函数，真是没找到在哪里

**Comment by fujohnwang** [comment]
代码都是临时的， 不是完整的项目， 只是为了说明问题

**Comment by fujohnwang** [comment]
@sixtrees import static com.codahale.metrics.MetricRegistry.name;.
