### ISSUE TITLE
一堆错误啊、、、、、

### ISSUE THREAD

**Issue by edocevol** [fujohnwang/unveil-springboot-feedbacks#5]
@Before("publicMethods() && annotation(countedAnnotation)")
    public void instrumentCounted(JoinPoint jp, Counted countedAnnotation)
    {
        String name= name(jp.getTarget().getClass(), StringUtils.hasLength(countedAnnotation.name())?
                countedAnnotation.name():jp.getSignature().getName(),"counter");
        Counter counter = counters.computeIfAbsent(name,key->metricRegistry.counter(java.lang.String.valueOf(key)));
    }

```
@Before("publicMethods()&&annotation(meteredAnnotaion)")
public void instrumentMetered(JoinPoint jp, Metered meteredAnnotaion)
{
    String name=name(jp.getTarget().getClass(),StringUtils.hasLength(meteredAnnotaion.name())?meteredAnnotaion.name():jp.getSignature().getName(),"meter");
}
```

**Comment by fujohnwang** [comment]
你是说代码错误还是啥？  r如果是你在另一个issue里提的编译错误，那么，请先确认你了解java基础的静态import特性 ；）

**Comment by edocevol** [comment]
额，意思是看你的书代码跑不起来，新手有点费力～[好难过],点击[ http://pinyin.cn/e26186 ]查看表情

发自我的小米手机在 扶墙老师 notifications@github.com，2016年6月22日 下午4:05写道：你是说代码错误还是啥？

**Comment by fujohnwang** [comment]
https://yunpan.cn/cRiuHFmYAwXjf （提取码：b976）

其实， 给你代码也跑步起来， 更多是希望读者自己搞明白原理， 不过，既然你要，那就放这里吧， 有些项目创建纯粹只是为了放代码的，不一定构建成功。

**Comment by edocevol** [comment]
嗯嗯，谢谢老师～前一封邮件没说清楚，我把你的书基本上看完了，现在在巩固周边的知识，提问的时候还不咋明白。非常感谢您的回复～

发自我的小米手机在 扶墙老师 notifications@github.com，2016年6月27日 下午2:06写道：https://yunpan.cn/cRiuHFmYAwXjf （提取码：b976）

其实， 给你代码也跑步起来， 更多是希望读者自己搞明白原理， 不过，既然你要，那就放这里吧， 有些项目创建纯粹只是为了放代码的，不一定构建成功。

**Comment by booom** [comment]
来晚了，云盘挂了，福强老师能否再分享一次源码？或者哪位有源码的同学能否代福强老师分享一下，谢谢啊:)
@sixtrees @yamtg

**Comment by stevenxiale** [comment]
云盘失效了 谁能再贴一下代码

**Comment by gitstudy007** [comment]
云盘404了

**Comment by KevinZMan** [comment]
https://yunpan.cn/cRiuHFmYAwXjf--云盘失效404了

**Comment by unnnnhappy** [comment]
可不可以再分享一下云盘

**Comment by fujohnwang** [comment]
artifacts lost, sorry, guys
