### ISSUE TITLE
WebApi的隐式转换的问题

### ISSUE THREAD

**Issue by unclezhao** [fujohnwang/unveil-springboot-feedbacks#6]
请教一下，如果使用隐式转换，在controller的方法中直接返回对应的DTO就可以了，但是如果失败呢？需要返回errcode和errmsg怎么处理？使用异常传过去？

在HttpMessageConverter中还将返回结果重新包装成WebApiResponse吗？

**Comment by fujohnwang** [comment]
只要你能在HttpMessageConverter中提取特征， 传什么都可以， 实现的细节上完全可以根据具体选择来决定。

如果无法区分不同的情况，那肯定就没法实现隐士转换了
