### ISSUE TITLE
勘误能直接反应到电子版上面吗？

### ISSUE THREAD

**Issue by yuxh** [fujohnwang/unveil-springboot-feedbacks#9]
《网易云阅读》上有这本书，但你的勘误没有修改上去。这种电子版的修改应该方便吧？

**Comment by fujohnwang** [comment]
这个是出版社来跟进的， 整个产业链我干预不了，需要第二版才行， 其实很多内容都是出版链条上其他人导致的，我原稿也没有那么多问题。
